environment: "<%= ENV['ENV_NAME'] %>"
hbx_id: "<%= ENV['HBX_ID'] %>"
invalid_argument_queue: "<%= ENV['HBX_ID'] %>.errors.invalid_arguements"
processing_failure_queue: "<%= ENV['HBX_ID'] %>.errors.processing_failures"
event_exchange: "<%= ENV['HBX_ID'] %>.<%= ENV['ENV_NAME'] %>.e.topic.events"
event_publish_exchange: "<%= ENV['HBX_ID'] %>.<%= ENV['ENV_NAME'] %>.e.fanout.events"
request_exchange: "<%= ENV['HBX_ID'] %>.<%= ENV['ENV_NAME'] %>.e.direct.requests"
amqp_uri: "amqp://<%= ENV['RABBITMQ_USERNAME'] %>:<%= ENV['RABBITMQ_PASSWORD'] %>@<%= ENV['RABBITMQ_HOST'] %>:<%= ENV['RABBITMQ_PORT'] %>"
email_from_address: "<%= ENV['EMAIL_FROM_ADDRESS'] %>"
smtp_host: "<%= ENV['SMTP_HOST'] %>"
smtp_port: "<%= ENV['SMTP_PORT'] %>"
email_username: "<%= ENV['SMTP_USERNAME'] %>"
email_password: "<%= ENV['SMTP_PASSWORD'] %>"
email_domain: "<%= ENV['EMAIL_DOMAIN'] %>"
